image: davxy/c-builder

stages:
    - build
    - test
    - deploy

# Build
build:
    stage: build
    script:
        - make

# Test
test:
    stage: test
    dependencies:
        - build
    script:
        - make test CONFIG=config/config-ci.mk
        - (cd test; valgrind --leak-check=full --error-exitcode=2 ./test -v)
        - gcovr --exclude test -r . | grep TOTAL
