image: davxy/linux-builder

stages:
    - build
    - test
    - deploy

# Build
build:
    stage: build
    script:
        - make

# Test
test:
    stage: test
    dependencies:
        - build
    script:
        - make test CONFIG=config/config_ci.mk
        - (cd test; valgrind --leak-check=full --error-exitcode=2 ./test)
        - gcovr --exclude test -r . | grep TOTAL

# Deploy
deploy:
    stage: deploy
    dependencies:
        - test
    only:
        - tags
    script:
        - make doc
