image: davxy/builder

stages:
    - build
    - test
    - deploy

# Build
build:
    stage: build
    script:
        - make

# Test
test:
    stage: test
    dependencies:
        - build
    script:
        - make test
        - (cd test; time ./test)
        - gcovr --exclude test -r . | grep TOTAL

# Deploy
deploy:
    stage: deploy
    dependencies:
        - test
    only:
        - tags
    script:
        - make doc
