image: davxy/linux-builder

stages:
    - build
    - test
    - deploy

# Build
build:
    stage: build
    script:
        - make
    tags:
        - gcc

# Test
test:
    stage: test
    dependencies:
        - build
    script:
        - make test CONFIG=config/config-ci.mk
        - (cd test; valgrind --leak-check=full --error-exitcode=2 ./test)
        - gcovr --exclude test -r . | grep TOTAL
    tags:
        - gcc

# Publish API Documentation
pages:
    stage: deploy
    dependencies:
        - test
    script:
        - make doc
        - mv doc/doxy/html/* public/
    artifacts:
        paths:
            - public
    only:
        - tags
