image: davxy/sonar-builder

stages:
    - deploy

# Publish API Documentation
pages:
    stage: deploy
    script:
        - ln -s /docs public
        - make doc
        - mv doc/doxy/html/ public/
        - pwd
        - ls -al
        - ls public/
    artifacts:
        paths:
            - public
