image: davxy/linux-builder

stages:
    - build
    - test
    - sonar
    - deploy

# Build
build:
    stage: build
    script:
        - make

# Test
test:
    stage: test
    dependencies:
        - build
    script:
        - make test
        - (cd test; time ./test)
        - gcovr --exclude test -r . | grep TOTAL

# Sonar
sonar:
    stage: sonar
    dependencies:
        - test
    only:
        - tsc
    script:
        - make sonar

# Deploy
deploy:
    stage: deploy
    dependencies:
        - test
    only:
        - tags
    script:
        - make doc
