image: davxy/sonar-builder

stages:
    - build
    - test
    - sonar
    - deploy

# Build
build:
    stage: build
    script:
        - make

# Test
test:
    stage: test
    dependencies:
        - build
    script:
        - make test CONFIG=config/config-ci.mk
        - (cd test; valgrind --leak-check=full --error-exitcode=2 ./test)
        - gcovr --exclude test -r . | grep TOTAL

# Sonar
sonar:
    stage: sonar
    dependencies:
        - test
    only:
        - tsc
    script:
        - make sonar CONFIG=config/config-ci.mk

# Deploy
deploy:
    stage: deploy
    dependencies:
        - test
    only:
        - tags
    script:
        - make doc
